# Name of the package if any. Package.ModuleName will be the module name 
package_name = "triqs_modest"

# The documentation string of the module. 
documentation = '''Functions to calculate the total electron density of lattice Green's functions using different methods 
and methods for chemical potenital searching given a target density.

Calculate the total electronic density from the lattice Green's function and search for the chemical potential that gives a 
target electron count. We provide several algorithms optimized for speed and robustness. Due to the modularity you can also 
leverage external root finding routines to write a custom chemical potential search.
'''

# Namespace. 
# Only the classes/functions/enums declared in this namespace will be wrapped
namespaces = "triqs triqs::modest"

# Match/reject elements according to regex
# If match_names/match_names are both set, filter for all elements 
# Algorithm is (for an element X of fully qualified name Qname)
#    if match_names and not match_names match Qname : skip X
#    if reject_names and reject_names match Qname : skip X
#    else keep X.

# JML TODO: delta_G0_C_k_sigma and trace_forces are temporarily exposed for debugging purposes.
# JML TODO: These should be removed from the match pattern once debugging is complete.
match_names = "triqs::modest::(density|find_chemical_potential|density_nk|forces|delta_G0_C_k_sigma|trace_forces)"

# Only keep elements declared in files matching the pattern
# match_files = "" # String must be a regex

exclude_system_headers = false
wrap_no_arg_methods_as_properties = true
